---
- name: Cài đặt K3s Master trên VM1
  hosts: master
  become: yes
  vars:
    internal_ip: "192.168.100.233"
    floating_ip: "192.168.121.xxx" # Thay bằng Floating IP thực tế của bạn
  tasks:
    - name: Tải và cài đặt K3s Server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip={{ internal_ip }} --advertise-address={{ internal_ip }} --tls-san={{ floating_ip }}" sh -
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Chờ k3s server khởi động
      service:
        name: k3s
        state: started
        enabled: yes

    - name: Lấy Node Token để join worker
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Lưu Node Token vào file tạm
      copy:
        content: "{{ node_token.stdout }}"
        dest: /tmp/k3s_node_token
